2021-12-05 17:53:09,984 INFO    MainThread:29258 [wandb_setup.py:_flush():71] setting env: {}
2021-12-05 17:53:09,984 INFO    MainThread:29258 [wandb_setup.py:_flush():71] setting login settings: {}
2021-12-05 17:53:09,984 INFO    MainThread:29258 [wandb_init.py:_log_setup():371] Logging user logs to /media/avidbeam/workspace/Abdelrahman_Workspace/Project_Codes/Synergy/wandb/run-20211205_175309-1oyvcl3v/logs/debug.log
2021-12-05 17:53:09,984 INFO    MainThread:29258 [wandb_init.py:_log_setup():372] Logging internal logs to /media/avidbeam/workspace/Abdelrahman_Workspace/Project_Codes/Synergy/wandb/run-20211205_175309-1oyvcl3v/logs/debug-internal.log
2021-12-05 17:53:09,984 INFO    MainThread:29258 [wandb_init.py:init():404] calling init triggers
2021-12-05 17:53:09,984 INFO    MainThread:29258 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2021-12-05 17:53:09,984 INFO    MainThread:29258 [wandb_init.py:init():449] starting backend
2021-12-05 17:53:09,984 INFO    MainThread:29258 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-12-05 17:53:09,999 INFO    MainThread:29258 [backend.py:ensure_launched():199] starting backend process...
2021-12-05 17:53:10,012 INFO    MainThread:29258 [backend.py:ensure_launched():204] started backend process with pid: 29340
2021-12-05 17:53:10,012 INFO    MainThread:29258 [wandb_init.py:init():458] backend started and connected
2021-12-05 17:53:10,013 INFO    MainThread:29258 [wandb_init.py:init():519] updated telemetry
2021-12-05 17:53:10,047 INFO    MainThread:29258 [wandb_init.py:init():549] communicating current version
2021-12-05 17:53:10,720 INFO    MainThread:29258 [wandb_init.py:init():554] got version response 
2021-12-05 17:53:10,720 INFO    MainThread:29258 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-12-05 17:53:40,722 INFO    MainThread:29258 [interface_queue.py:_communicate_run():336] couldn't get run from backend
2021-12-05 17:53:40,723 ERROR   MainThread:29258 [wandb_init.py:init():569] backend process timed out
2021-12-05 17:53:40,723 ERROR   MainThread:29258 [wandb_init.py:init():578] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2021-12-05 17:53:40,730 ERROR   MainThread:29258 [wandb_init.py:init():944] error
Traceback (most recent call last):
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 917, in init
    run = wi.init()
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 582, in init
    backend.cleanup()
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 228, in cleanup
    self.interface.join()
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/wandb/sdk/interface/interface_queue.py", line 481, in join
    super(InterfaceQueue, self).join()
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 591, in join
    self._communicate_shutdown()
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/wandb/sdk/interface/interface_queue.py", line 478, in _communicate_shutdown
    _ = self._communicate(record)
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/wandb/sdk/interface/interface_queue.py", line 232, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/wandb/sdk/interface/interface_queue.py", line 237, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
