
   1/3266 [..............................] - ETA: 1:43:31 - train_loss: 3239.5449
Epoch 1/500:
2021-12-05 12:52:25.700963: I tensorflow/stream_executor/cuda/cuda_dnn.cc:366] Loaded cuDNN version 8100

































 226/3266 [=>............................] - ETA: 14:23 - train_loss: 1933.3209
Traceback (most recent call last):
  File "train.py", line 40, in <module>
    train(model, training_data_generator, validation_data_generator, 500,\
  File "/media/avidbeam/workspace/Abdelrahman_Workspace/Project_Codes/Synergy/utils/custom_fit.py", line 32, in train
    train_loss = train_batch(X_batch,\
  File "/media/avidbeam/workspace/Abdelrahman_Workspace/Project_Codes/Synergy/utils/custom_fit.py", line 66, in train_batch
    y_pred = model(X, training=True)
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
    return fn(*args, **kwargs)
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1083, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 92, in error_handler
    return fn(*args, **kwargs)
  File "/media/avidbeam/workspace/Abdelrahman_Workspace/Project_Codes/Synergy/model/synergy.py", line 56, in call
    X = self.mobileNet(batch_images)
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
    return fn(*args, **kwargs)
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1083, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 92, in error_handler
    return fn(*args, **kwargs)
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/keras/engine/functional.py", line 451, in call
    return self._run_internal_graph(
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/keras/engine/functional.py", line 589, in _run_internal_graph
    outputs = node.layer(*args, **kwargs)
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
    return fn(*args, **kwargs)
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1083, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 92, in error_handler
    return fn(*args, **kwargs)
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/keras/layers/normalization/batch_normalization.py", line 767, in call
    outputs = self._fused_batch_norm(inputs, training=training)
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/keras/layers/normalization/batch_normalization.py", line 654, in _fused_batch_norm
    self.add_update(variance_update)
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1776, in add_update
    update()  # pylint: disable=not-callable
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/keras/layers/normalization/batch_normalization.py", line 648, in variance_update
    return self._assign_new_value(self.moving_variance, variance)
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/keras/layers/normalization/batch_normalization.py", line 539, in _assign_new_value
    return variable.assign(value, name=scope)
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 915, in assign
    assign_op = gen_resource_variable_ops.assign_variable_op(
  File "/home/avidbeam/.virtualenvs/TensorFlow_2/lib/python3.8/site-packages/tensorflow/python/ops/gen_resource_variable_ops.py", line 141, in assign_variable_op
    _result = pywrap_tfe.TFE_Py_FastPathExecute(
KeyboardInterrupt